name: curio_spark
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.5.0"

dependencies:
  rxdart: ^0.28.0
  permission_handler: ^11.0.1
  speech_to_text: ^7.0.0
  http: ^1.3.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  device_preview: ^1.1.0
  shared_preferences: ^2.2.0
  provider: ^6.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter_local_notifications: ^19.1.0
  timezone: ^0.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  
flutter:

  uses-material-design: true

  assets:
    - assets/images/icon/icon.png
    - assets/images/icon/idea.png
    - assets/images/icon/better.png

flutter_launcher_icons:
  image_path: "assets/images/icon/better.png"
  android: true
  ios: true
  remove_alpha_ios: true
